### ISSUE TITLE
Karpenter nodes terminates immediately due to controller.interruption initiating delete from interruption message

### ISSUE THREAD

**Issue by thepoppingone** [aws/karpenter-provider-aws#4935]
### Description

**Observed Behavior**:
Karpenter nodes get launched and deleted immediately, and pods get stuck at pending

**Expected Behavior**:
Expected behaviour to allocate pods and nodes to be not killed

**Reproduction Steps** (Please include YAML):
```
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  labels:
    intent: apps
limits:
  resources:
    cpu: 1k
  providerRef:
    name: default
  requirements:
  - key: karpenter.k8s.aws/instance-category
    operator: In
    values:
    - m
  - key: karpenter.k8s.aws/instance-cpu
    operator: In
    values:
    - "2"
   - key: karpenter.k8s.aws/instance-generation
    operator: In
    values:
    - "5"
    - "6"
  - key: karpenter.sh/capacity-type
    operator: In
    values:
    - spot
 - key: kubernetes.io/arch
    operator: In
    values:
    - amd64
  - key: kubernetes.io/os
       operator: In
       values:
       - linux
  ttlSecondsAfterEmpty: 30
```

**Versions**:
- Chart Version: v0.31.0
- Kubernetes Version (`kubectl version`):  v1.27

```
2023-10-26T09:41:06.888Z    INFO    controller.machine.lifecycle    launched machine    {"commit": "322822a", "machine": "default-n2tl5", "provisioner": "default", "provider-id": "aws:///ap-southeast-1a/i-06381788068af94ad", "instance-type": "m5a.large", "zone": "ap-southeast-1a", "capacity-type": "on-demand", "allocatable": {"cpu":"1930m","ephemeral-storage":"44Gi","memory":"6903Mi","pods":"29","vpc.amazonaws.com/pod-eni":"9"}}
2023-10-26T09:41:07.098Z    INFO    controller.machine.lifecycle    launched machine    {"commit": "322822a", "machine": "default-hd9ld", "provisioner": "default", "provider-id": "aws:///ap-southeast-1a/i-0587faa3ca1b921b2", "instance-type": "m5a.large", "zone": "ap-southeast-1a", "capacity-type": "on-demand", "allocatable": {"cpu":"1930m","ephemeral-storage":"44Gi","memory":"6903Mi","pods":"29","vpc.amazonaws.com/pod-eni":"9"}}
2023-10-26T09:41:07.992Z    INFO    controller.interruption initiating delete from interruption message {"commit": "322822a", "queue": "Karpenter-eks-bh-drupal-cms-dev", "messageKind": "StateChangeKind", "machine": "default-c2vwb", "action": "CordonAndDrain"}
2023-10-26T09:41:08.077Z    INFO    controller.interruption initiating delete from interruption message {"commit": "322822a", "queue": "Karpenter-eks-bh-drupal-cms-dev", "messageKind": "StateChangeKind", "machine": "default-n2tl5", "action": "CordonAndDrain"}
2023-10-26T09:41:08.189Z    INFO    controller.interruption initiating delete from interruption message {"commit": "322822a", "queue": "Karpenter-eks-bh-drupal-cms-dev", "messageKind": "StateChangeKind", "machine": "default-hd9ld", "action": "CordonAndDrain"}
2023-10-26T09:41:08.506Z    INFO    controller.machine.termination  deleted machine {"commit": "322822a", "machine": "default-n2tl5", "provisioner": "default", "node": "", "provider-id": "aws:///ap-southeast-1a/i-06381788068af94ad"}
2023-10-26T09:41:08.513Z    INFO    controller.machine.termination  deleted machine {"commit": "322822a", "machine": "default-c2vwb", "provisioner": "default", "node": "", "provider-id": "aws:///ap-southeast-1a/i-02fbccda0dc610720"}
2023-10-26T09:41:08.537Z    INFO    controller.machine.termination  deleted machine {"commit": "322822a", "machine": "default-hd9ld", "provisioner": "default", "node": "", "provider-id": "aws:///ap-southeast-1a/i-0587faa3ca1b921b2"}
```

Why is Karpenter doing cordoning and draining? There are no other errors shown on the logs. We turned off consolidation and use ttlSecondsAfterEmpty

**Comment by Imunhatep** [comment]
To save up some time - there is a thread, that basically states how consolidation option is not production ready for most use cases #3059

**Comment by thepoppingone** [comment]
@Imunhatep We tried setting consolidation to false but still facing this issue. Do we have to remove `ttlSecondsAfterEmpty` as well?

**Comment by Imunhatep** [comment]
From logs it seen that instance is removed a second after creation.. 
Haven't seen such behaviour in case of disabled consolidation option. 

Yet I see an inconsistance in definition and logged info:
logs contain `"capacity-type": "on-demand",`

yet provider states: 
```
key: karpenter.sh/capacity-type
    operator: In
    values:
    - spot
```

Not sure here, as we don't use spot instances, but might indicate some bug or miss/not in sync conifguration.

p.s.
I'm not a mainteiner, so please take my words as assumptions rather than statements.

**Comment by njtran** [comment]
@thepoppingone The instance type requirements you've put down restrict the instances to m5*.large and m6*.large instances. Can you try a larger set of instance types with lower rates of interruption? 

I'm also curious how there's on-demand instances being launched when you have a spot requirement. Can you ensure the provisioner you're using is the one that you used when encountering this? I wasn't able to see this happen with my cluster.

Additionally, the logs are indicating there was a state change with the instance associated to your node. Are you doing anything to the instances? https://github.com/aws/karpenter/blob/v0.31.0/pkg/controllers/interruption/controller.go#L230-L236

To @Imunhatep's point, I'm not sure why Consolidation is mentioned here, as there's no mention of it in the logs and it's not enabled in the provisioner. The issue should only be related to the interruption code.
Additionally, Consolidation is definitely ready for production workloads, and we've heard feedback that indicates that, yet there's always room to improve the Consolidation experience, especially for users with more specific requirements on utilization-based disruption, which is why we're highly prioritizing the consolidation TTL issue that you've linked.

**Comment by Imunhatep** [comment]
Consolidation was mentioned in the initial description, yet it wasn't mentioned when consolidation was turned off - before or after encountered issue.

p.s.
_As someone responsible for maintaining a solution that depends on Karpenter within our company, I'm [interested](https://github.com/aws/karpenter/issues/3921) in enabling consolidation option. However, my preference lies in ensuring a peaceful night's rest rather than dealing with the consequences of production-ready features.._

**Comment by njtran** [comment]
@thepoppingone theorizing here, can you check if the interruption queue is the one that was created for your cluster? Do you have multiple clusters using the same interruption queue?

**Comment by tzneal** [comment]
@thepoppingone Are you still seeing this issue? I checked and both instances failed to launch correctly.

**Comment by thepoppingone** [comment]
We undeployed Karpenter for this cluster. Maybe would try the 0.32.x series to see if it will work

**Comment by nakulrao** [comment]
I'm having the same issue, any updates on this?

**Comment by jonathan-innis** [comment]
Do you know if the instance is trying to encrypt any of the volumes? Typically when we are seeing instances fail to stay up as soon as they are launched, this typically means there is some type of default encryption key that is being used in the account and the NodeRole that is being used to launch instances doesn't have something like `kms:GenerateDataKeyWithoutPlaintext` permissions against the encryption key.

**Comment by nakulrao** [comment]
@jonathan-innis you absolute legend. That was the issue! Looks like i had added the node role instead of the IRSA role to the KMS Principal. This explains why the instances were immediately terminating. Thank you so much!

**Comment by jonathan-innis** [comment]
Glad that helped @nakulrao! 

@thepoppingone Was this your issue as well?

**Comment by lishuaisky** [comment]
I have the same issue

**Comment by jonathan-innis** [comment]
> I have the same issue

@lishuaisky Do you have any more detail on if the root cause of your issue is different or was it the same root cause and the mitigation worked as expected?

**Comment by snorlaX-sleeps** [comment]
@jonathan-innis - which role requires the `kms:GenerateDataKeyWithoutPlaintext` permissions, the Karpenter role or the actual Node role?
Running into this issue with some EBS volumes

**Comment by ceastman-r7** [comment]
Would this explain this error in the logs? 
karpenter-7bf4d8d4c5-z7r4j controller 2023-11-29T18:32:00.263Z	ERROR	controller	Reconciler error	{"commit": "709030d", "controller": "machine.lifecycle", "controllerGroup": "karpenter.sh", "controllerKind": "Machine", "Machine": {"name":"karpenter-on-demand-pfnxb"}, "namespace": "", "name": "karpenter-on-demand-pfnxb", "reconcileID": "45e2f3ff-b07f-4627-a5fb-8179707bafb6", "error": "launching machine, creating instance, with fleet error(s), InvalidBlockDeviceMapping: Cannot create unencrypted device /dev/xvda from encrypted snapshot"}

**Comment by snorlaX-sleeps** [comment]
Still unsure where the policy needed added (gave it to the worker IAM role and karpenter), however adding [this](https://karpenter.sh/docs/troubleshooting/#node-terminates-before-ready-on-failed-encrypted-ebs-volume) policy to a KMS key I did not know about ended up resolving it (so still unsure if both were the fix)

**Comment by vjkancherla** [comment]
Hi @snorlaX-sleeps, I was seeing the same error as you today and I did the following to identify the root cause:

- Went to CloudTrail and search/filtered using event name set to "GenerateDataKeyWithoutPlaintext".
- All my GenerateDataKeyWithoutPlaintext events had the following error message:
```
"errorMessage": "User: arn:aws:sts::xxxxxxxx:assumed-role/karpenter-20231204131600471600000002/1701700196698666540 is not authorized to perform: kms:GenerateDataKeyWithoutPlaintext on resource: arn:aws:kms:eu-west-2:xxxxxxxxxxx:key/7dac2551-1e4d-4c5d-b02e-296ef7126f4e because no identity-based policy allows the kms:GenerateDataKeyWithoutPlaintext action",
```
- I discovered that the EBS encryption KMS key we are using is not the default KMS key but a different, customer managed, KMS key. Karpenter IRSA does not have access to this KMS key
- As a test, I assigned AdminAccess policy to Karpenter's IRSA. The nodes are now being successfully provisioned, without any issues.
- I will now add permissions to Karpenter's IRSA to enable access to the identified KMS key (in the error message), and remove the  AdminAccess policy, and test

**Comment by jonathan-innis** [comment]
> the Karpenter role or the actual Node role

You need to attach the permission to the IRSA role so that the Karpenter controller that is launching the instances has permission to create the grant that is needed by the EC2 instance to un-encrypt the volume.

**Comment by snorlaX-sleeps** [comment]
Thanks @vjkancherla @jonathan-innis - I will update our docs / deployment to include this permission

**Comment by jonathan-innis** [comment]
Closing this one out since it looks like this issue was resolved.

**Comment by marcoboi** [comment]
Thank you @jonathan-innis and @vjkancherla.
The issue seemed to lie with a lack of permission for the encryption service (KMS) in my case as well.
For the chronicles, here's a quick summary of how I got there:

0. To set up Karpenter, I've been following the example deployment reported [here](https://github.com/terraform-aws-modules/terraform-aws-eks/tree/19b79df055512a7d61641fc716c9a2c597c7d277/examples/karpenter). Note that:
a: my karpenter was deployed on fargate nodes
b: all karpenter pods were healthy
c: I used the [deployment reported here](https://karpenter.sh/docs/getting-started/getting-started-with-karpenter/#6-scale-up-deployment) in order to test autoscaling

1. When trying to scale up a service, the logs from karpenter's pods displayed the following sequence of messages: `found provisionable pod(s)`, `computed new nodeclaim(s) to fit pod(s)`, `created nodeclaim`, `launched nodeclaim`, `initiating delete from interruption message`, `controller.nodeclaim.termination`
2. I found that [encryption was enabled by default in EC2](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSEncryption.html#encryption-by-default)
3. Went into CloudTrail and could see a bunch of events with name `GenerateDataKeyWithoutPlaintext` matching the time at which the attempted scaling happened
4. In order to check the policy attached to the Karpenter's role, I went into IAM, Roles and looked for a Role named `KarpenterController` (the name obviously depends on how your deployment works). 
5. My role had only one policy attached. The policy was also named `KarpenterController`. I edited it to add the following block, as suggested by @vjkancherla. Note you can probably be more specific on the permission's scope, but the one I reported here worked for me.
```
{
    "Sid": "KarpenterEncryption",
    "Effect": "Allow",
    "Action": [
        "kms:GenerateDataKeyWithoutPlaintext",
        "kms:Decrypt",
        "kms:CreateGrant"
    ],
    "Resource": "*"
}
```
6. Deployed a single pod and could observe the nodes being created in the cluster a few instants after. Note that, in my setup, I had no nodes for custom workloads provisioned, so deploying even a single pod triggered the creation of a node)
7. Destroyed the deployment and the node was removed
