### ISSUE TITLE
Helm chart has non-default `dnsPolicy`

### ISSUE THREAD

**Issue by jclangst** [aws/karpenter-provider-aws#4947]
### Description

**Observed Behavior**:

The Karpenter Helm chart has a default `dnsPolicy` called `Default` ([link](https://github.com/aws/karpenter/blob/de4388d8b381bf6ce86a9da41d9c914698897e77/charts/karpenter/values.yaml#L55C2-L55C2)). Interestingly, this is not the default dns policy for Kubernetes which is `ClusterFirst` ([link](https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-dns-policy)).

I believe the intent with the chart was to use the default Kubernetes DNS settings as I do not believe there is any benefit in overriding the cluster defaults. I have verified `ClusterFirst` works as expected.

The current default setup is incompatible with clusters with injected sidecars that need `ClusterFirst` DNS resolution (e.g., service meshes such as Linkerd).

**Expected Behavior**:

`dnsPolicy` in the helm chart should be set to `ClusterFirst` as the default

**Reproduction Steps** (Please include YAML):

See the Helm chart. 

**Versions**:
- Chart Version: `v0.31`
- Kubernetes Version (`kubectl version`):  `v1.27.4-eks-2d98532`
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jonathan-innis** [comment]
This default policy was changed here: https://github.com/aws/karpenter/pull/2199. This was originally recommended from https://github.com/aws/karpenter/issues/2186 where a user informed us that there's a bit of an ordering problem if you want to scale up your `core-dns` pods based on Karpenter-managed capacity (since Karpenter would need DNS to be up first in the `ClusterFirst` mode). 

Are you running into any particular issues with the current default DNS policy? I believe you should be able to change this in the helm vaues if that default isn't working for your specific cluster.

**Comment by jclangst** [comment]
Yes, the current setting can cause issues. The most common use case is anytime you have injected sidecar containers (for example, all popular service meshes). These sidecars usually need access to the cluster dns servers and thus will be unable to launch due to this pod-level DNS setting.

I understand the issue presented in #2186 . However, it seems like running karpenter prior to even launching dns is going to be a niche setup that is unlikely to impact most users. I'd propose that the default should stay the kubernetes default in order to follow the principle of least surprise. 

If someone has a special case like running karpenter prior to their DNS they have the option to configure it. However, the current setting definitely deviates from normal practice and will impact all service mesh users at minimum.

**Comment by jonathan-innis** [comment]
I agree with you that we should probably follow the principle of least surprise here. Since using `Default` is not the `Default` setup, I could see this being surprising when installing the Karpenter deployment. 

I'm personally fine with removing the setting in the deployment. I think that we added this to the chart thinking that there were no downsides to doing this. Since changing this would be a breaking change to existing users, we should call this out in the Upgrade docs alongside providing guidance in the "Getting Started" guide around what you should do if you want Karpenter to manage your CoreDNS pods rather than having the CoreDNS pods up before Karpenter starts.
