### ISSUE TITLE
Discover Instance Type Capacity Memory Overhead Instead of `vmMemoryOverheadPercent`

### ISSUE THREAD

**Issue by jonathan-innis** [aws/karpenter-provider-aws#5161]
### Tell us about your request

We could consider a few options to discover the expected capacity overhead for a given instance type:
1. We could store the instance type capacity in memory once a version of that type has been launched and use that as the capacity value after the initial launch rather than basing our calculations off of some heuristic
2. We could launch instance types, check their capacity and diff the reported capacity from the actual capacity in a generated file that can be shipped with Karpenter on release so we always have accurate measurements on the instance type overhead.

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

Calculating the difference between the EC2-reported memory capacity and the actual capacity of the instance as reported by kubelet.

### Are you currently working around this issue?

Using a heuristic `vmMemoryOverheadPercent` value right now that is tunable by users and passed through `karpenter-global-settings`

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jonathan-innis** [comment]
This is a "transferred" version of the issue in `kubernetes-sigs/karpenter`: https://github.com/kubernetes-sigs/karpenter/issues/716

**Comment by sosheskaz** [comment]
Could a simple mitigation be to add a static setting? e.g. `vmMemoryOverheadOffset`, which would take a static amount of memory?

When running compute which is highly heterogeneous, but relatively large, this would simplify the practice of managing this setting, because a sufficiently large static overhead would be able to outweigh the percentage, and allow for less waste.

**Comment by BEvgeniyS** [comment]
The `vmMemoryOverheadOffset` value is clearly not one-size-fits-all, so making it per-nodepool would be a great start.

I prefer approach #<zws>1 because it doesn't tie Karpenter to cloud provider updates and can work even when new instance types appear before an update.

Here's how I imagine this could be implemented:
a) Convert it to something like "initVmMemoryOverheadOffset" and make it a per-nodepool setting.
b) As soon as we discover or launch a single node of any given nodepool/instanceType pair, the node allocatable should be dynamically discovered and stored in memory or optionally in some form of permanent storage. If Karpenter restarts, it can rediscover this information. All systemReserved/kubeReserved and Bottlerocket's control/admin containers subtract from the allocatable, and should already be considered in the proper allocatable exposed by kubelet.
Karpenter already is able to calculate daemonset overhead, so this can be factored in

The remaining issue is that if the value is too high, Karpenter won't be able to launch the node even though the capacity is there. #<zws>2 can then be used as an initial hint for known types.

**Comment by Balraj06** [comment]
@jonathan-innis Any latest updates on this issue.

**Comment by jukie** [comment]
I don't think the NodeOverlay RFC is a good way to address this. If the Overhead can be automatically discovered that should be an option vs requiring a user to configure for every single instance type themselves.

**Comment by youwalther65** [comment]
Agree in that CA has to do an easier job, but even CA does include some delta to accommodate for [slight changes](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/config/autoscaling_options.go#L74-L81) between instance types in same or similar NodePool/ASG etc (something just visible in main.go and not yet described in CA FAQ)
Having a combination of NodePool and instance type might be somehow safe, because a NodePool is tight to an EC2NodeClass. But underlying AMI version of NodePool might change over time and AMI and/or custom user data can tweak kubeReserved and systemReserved in different ways leading to new values of allocatable. So we should think of re-evaluate the cached value.
Another point just to mention is how DaemonSet overhead is factored in: Some DS can be applied to only a subset of nodes via taints/tolerations, so

**Comment by BEvgeniyS** [comment]
> So we should think of re-evaluate the cached value.

cached value is not static, it gets updated during node registration. Cache is also flushed if nodepool hash is changed. DS overhead is factored in already, don't think we need to change anything there

**Comment by jukie** [comment]
I'd like to start an RFC on this, does this sound like a reasonable start?
* Use an in-memory cache to store per instance-type overhead memory values
* Pre-populate overhead memory values for all known instance types via similar implementation as https://github.com/aws/karpenter-provider-aws/pull/4517. This value can change so still needs to be accounted for but provides a better initial value over `vmMemoryOverheadPercent`
* Unknown instance types (For example when a new instance type becomes available) would default to `vmMemoryOverheadPercent` calculations
* Every time a NodeClaim is created with a particular instance type the cached value gets updated

If it hasn't been mentioned or discussed elsewhere, could a feature request be opened with the EC2 team and SDK maintainers to provide this information in the `DescribeInstanceTypes` API?

**Comment by jukie** [comment]
Thanks for explaining that, I hadn't given it enough thought! What you've mentioned for a cache mapping of instance-type + ami version to overhead makes sense.

**Comment by jukie** [comment]
Caching per-ami is proving to be difficult as that would introduce some coupling. I've got some WIP code [here](https://github.com/aws/karpenter-provider-aws/pull/7004) that would cover per-amiFamily and uses the nodeClass hash as a key.

Specifically here https://github.com/aws/karpenter-provider-aws/blob/main/pkg/cloudprovider/cloudprovider.go#L286-L288 I'm not sure where to store and/or how to compare an instance type that maps to a particular AMI version.

**Comment by jukie** [comment]
@youwalther65 would it be better to use a cache key with instance type name + hash of the AMI names in NodeClass status?

That might be the safest route but would mean the first node that gets launched after an AMI would fallback to vmMemoryOverheadPercent.

**Comment by youwalther65** [comment]
@jonathan-innis What do you think about the idea from @jukie ?
