### ISSUE TITLE
kubernetes setup for Karpenter contribution

### ISSUE THREAD

**Issue by sasanknvs** [aws/karpenter-provider-aws#5179]
I want to contribute to karpenter. I have gone through the "Contributing" section in Karpenter documentation. I was able to setup the tools on my machine like Go, Kubectl, make and helm.  But I could not find enough information about kubernetes setup. 

1. Should kubernetes setup needs to be done only on AWS EKS ?
2. Can kubernetes be setup locally using micro k8s or k3s ? if do it locally how can karpenter provision new nodes ?
3. Also regarding ECR, can I run a container with docker registry and use as a docker repository instead of AWS ECR ?
4. Also if we need to do all of it in AWS, is Free tier subscription enough ?

Please clarify the above so that I can also contribute.

**Comment by jmdeal** [comment]
I'm going to link this here as well: https://github.com/aws/karpenter-provider-aws/issues/5223. This issue is going to track improving our contribution documentation (including, but not limited to, setup). I'm going to close out this issue for now since I think the specific questions were answered (feel free to re-open though).
