### ISSUE TITLE
Weighted node pools concept

### ISSUE THREAD

**Issue by runningman84** [aws/karpenter-provider-aws#5201]
### Description

**How can the docs be improved?**

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

I am having multiple node pools

* arm-instance-store (weight 35, arm taint) eg. m5gd
* arm (weight 30, arm taint) eg. m5g
* x86-instance-store (weight 25) eg. m5ad
* x86 (weight 20) eg. m5a

It turns out that pods which tolerate arm always are scheduled to the arm-instance-store, pods which do not tolerate arm always are scheduled to the  x86-instance-store.

In a perfect world the price would decide which nodepool to use. The weight should just be the decision maker if multiple pools have the same pricing.

From the docs it is unclear to me if my setup would already accomplish that. 

This is also linked to https://github.com/aws/karpenter/issues/5157 which would be needed to have the correct pricing applied.

**Comment by jmdeal** [comment]
If a pod is compatible with multiple `NodePool`s, the `NodePool` with the greater weight will be selected regardless of instance price. This is because there are instances where it is important to prioritize one `NodePool` over another regardless of price and weight provides a mechanism to do so. 

Are you able to further explain your use case? If you have instances which can schedule on either `NodePool`, it may make sense to create a `NodePool` which includes all of those instance types for those workloads to schedule against. Then Karpenter would be able to choose the cheapest possible node.

**Comment by runningman84** [comment]
The issue is that I cannot have them in the same nodepool because my goal is to save costs.

I do this by leveraging the instance store volume for container images. If I do not have instance storage available I have to assign a lot more ebs storage to compensate for the missing instance volume.

In our usecase we saw savings of more than 20 percent by leveraging the instance storage instead of expensive ebs volumes.

**Comment by runningman84** [comment]
Maybe if both node pool have the same priority karpenter could just decide on the pricing?

**Comment by jmdeal** [comment]
Ok, I think I understand your use case. To confirm, is it always preferable to use instances with built-in storage over their counterparts when a workload needs that storage? Or is there a case where it would be cheaper to use EBS with a normal instance that you want Karpenter to account for? Or are there workloads that don't need the storage that you want to schedule to the normal instance?

**Comment by runningman84** [comment]
My workloads are always performing  better using instance storage. But they work on normal instances too the startup time is just slower.

My main goal is to save costs.

Due too spot market pricing a scenario could occur in which normal instance + additional ebs for the lack of instance store is cheaper than an instance storage node.

**Comment by jonathan-innis** [comment]
Ah, got it. So in an ideal scenario, we would consider the pricing of the EBS volumes and you wouldn't have to specify weighting at all? It sounds like the weighting right now is serving as a proxy to tell Karpenter that it should prefer instance storage instance types first before it should consider other instance types due to the "EBS volume discount" that you get when you don't have to launch EBS volumes due to NVME storage, but this doesn't quite work because we only consider NodePools locally.

This is somewhat related to https://github.com/aws/karpenter/issues/3714 where we have multiple preferences that are interacting with weights here; however, seems like what you are really looking for here is for us just to consider EBS pricing when choosing instance types so that we always pick the best instance type, considering this storage cost.

**Comment by runningman84** [comment]
Yes that’s right but due to karpenters design we have to have two nodepools because the storage configuration is in the ec2 node class and we cannot use the same config for both scenarios.

**Comment by runningman84** [comment]
Unstale

**Comment by runningman84** [comment]
@jmdeal can convert that to a feature too?

**Comment by jmdeal** [comment]
If I understand correctly your particular issue would be solved by a feature which addresses #5157 and this would be more of a temporary measure to get the desired behavior until Karpenter considers EBS pricing. Is there a reason you would want to see this change as well as #5157, rather than just #5157? Changing the behavior of weights as proposed would be a large breaking change which would break a lot of current customer use-cases (e.g. #4652).

**Comment by runningman84** [comment]
The feature #5157 would not be enough because you have to configure instance store nodes and normal nodes in a different way…

**Comment by jonathan-innis** [comment]
> would not be enough because you have to configure instance store nodes and normal nodes in a different way

Is this the case anymore now that #4735 is merged? You should now be able to use a single EC2NodeClass to configure both NVME and non-NVME in the same NodePool. 

The other one to keep an eye on is #4701 since that would enable you to get the EBS storage sizing correct alongside the instance store volume support. 

This is currently tough through the CreateFleet call that we have and the PCO allocation strategy that we are using to select instances. AFAIK, price-capacity optimized doesn't currently consider this so we'd need this as well, since there's currently no way for us to pass this difference in priority through our current allocation strategy.

**Comment by runningman84** [comment]
Even if the native instance storage support is available you would like to have a smaller root/data volume if you use the instance storage. Otherwise you would not save any money.

I haven seen how this is addressed in any of the linked issues.

**Comment by jonathan-innis** [comment]
> Even if the native instance storage support is available you would like to have a smaller root/data volume if you use the instance storage. Otherwise you would not save any money

That's why I was thinking that #2394 would be a good solve for your problem. If we could dynamically size everything, now we can use a single NodePool to reference everything, including the instance store volumes AND the EBS volumes
