### ISSUE TITLE
Consolidation should be able to split one larger node to two cheaper nodes

### ISSUE THREAD

**Issue by runningman84** [aws/karpenter-provider-aws#5304]
### Description

**Observed Behavior**:

Karpenter tries to binpack workloads to big nodes in order to save overhead costs of daemonset and so on.

This behavior is rather expensive in our usecase. With the given pricing history of this week at is a lot cheaper to have 2 m5dn.xlarge instances instead of one m5dn.2xlarge.

m5dn.xlarge:

On-Demand
$0.3240
eu-central-1a
$0.1383
$0.0346 per vCPU
57.31% saving
eu-central-1b
Cheapest
$0.1348
$0.0337 per vCPU
58.39% saving
eu-central-1c
$0.1477
$0.0369 per vCPU
54.40% saving

m5dn.2xlarge:

On-Demand
$0.6480
eu-central-1a
$0.3950
$0.0494 per vCPU
39.04% saving
eu-central-1b
Cheapest
$0.2903
$0.0363 per vCPU
55.21% saving
eu-central-1c
$0.3379
$0.0422 per vCPU
47.85% saving

**Expected Behavior**:

Karpenter should take the price per core into consideration and select 2 small instances instead of 1 big instance.

It should also take into account that a m5dn.xlarge has 4 cores but due too kubelet reservations only 3.5 cores are usable and a m5dn.2xlarge has 8 cores but has 7.5 usable cores... 

**Reproduction Steps** (Please include YAML):
na

**Versions**:
- Chart Version: 0.32.2
- Kubernetes Version (`kubectl version`): .1.28.x

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by njtran** [comment]
Just so I understand, are you expecting Karpenter to consolidate a m5dn.2xlarge to 2 m5dn.xlarges, or for a provisioning loop is it choosing the m5dn.2xlarge over the 2 m5dn.xlarge?  

In the case of Consolidation, the consolidation algorithm will only make a decision with at most one replacement node, which could prevent consolidating from a 2xlarge to 2 xlarge instances. Since these prices are usually pretty on the line of an xlarge being half the price of a 2xlarge, it's almost always cheaper from the overhead perspective to go with the larger node, but this may be an erroneous assumption that we've taken.

**Comment by runningman84** [comment]
I think there are two use cases:

2 pending pods, which need either one m5dn.2xlarge or two m5dn.xlarge instances
2 running pods on a m5dn.2xlarge instance, it might make sense to split them to two m5dn.xlarge instances

The first usecase seems to be pretty easy to detect and to implement, the second usecase is not so important because if the first usecase is implemented the second usecase would not appear very often...

$0.0346 per vCPU vs $0.0494 per vCPU is quite a difference from my point of view. Even if you account for 20% overhead on a smaller instances the smaller one would be still way cheaper.

The correct overhead could be even calculated by looking into the allocatable cores and memory and adding all daemon set requirements...

**Comment by njtran** [comment]
Where did you get the 0.0346 and 0.494 from? For on-demand prices, I'm looking at `m5dn.xlarge = $0.272` and `m5dn.2xlarge = $0.544` which is exactly half of the 2xlarge, same goes for the number of cores. In this case, it's technically more cost effective to get the larger node, because you're getting more capacity for slightly less. Let me know if I'm misunderstanding this.

> 2 running pods on a m5dn.2xlarge instance, it might make sense to split them to two m5dn.xlarge instances

The case here is that Karpenter doesn't see this as cheaper, unless the smaller instance is cheaper, since any combination of nodes that would tightly pack into 2 .xlarges, would pack more efficiently in one 2xlarge.

**Comment by runningman84** [comment]
I was getting this pricing difference in eu-central-1. Today the pricing for c5ad.large vs c5ad.xlarge had a similar issue where the smaller instance has way lower cpu core costs. I am speaking of the spot market... in ondemad a bigger box is always the best instance.

**Comment by njtran** [comment]
> 2 pending pods, which need either one m5dn.2xlarge or two m5dn.xlarge instances

This sounds like something Karpenter should already do for Provisioning if it's possible, which I think should cover the first use-case you're talking about here. The nodes would need to be pretty tightly packed to achieve this, but since the spot prices are different, and potentially not perfectly scaled, there should always be a combination for a given pods that is the _cheapest_ for Karpenter to select, as generating a set of pods that perfectly pack two `.xlarge` instances will be less packed if added together on a `2xlarge instance. 

For Consolidation, you're right that this won't happen, because Consolidation doesn't consolidate from 1 to 2 cheaper nodes. This is intentional, but could possible be changed in the future. I'll change the title of this issue to match this request.

**Comment by runningman84** [comment]
I think right now even in the provisioning phase it does not work as expected. That means it would rather get one big box instead of two smaller ones.

**Comment by njtran** [comment]
Can you share the logs and deployments and pods showing that? I think we'd need to see the price of the `.2xlarge` and the 2 `.xlarge` instances at the time you've shown, calculate the difference in price, and see if the overhead difference from the 2 `.xlarge` instances with the given pods is still cheaper in comparison to the .2xlarge. In most cases, you'd need small enough pod sizes and tight enough bin-packing for this to be chosen, which can often result in a larger instance off the bat. It'd be interesting to see your daemonsets too.
