### ISSUE TITLE
Keep log output path on v1+

### ISSUE THREAD

**Issue by calvinbui** [aws/karpenter-provider-aws#5352]
### Description

** READ BEFORE CONTINUING: If your issue is not specific to AWS, please cut a ticket in github.com/kubernetes-sigs/karpenter.

**What problem are you trying to solve?**

Reference: https://github.com/aws/karpenter-provider-aws/issues/5288#issuecomment-1855229201

- `logConfig` is currently deprecated and will be removed in v1.
- We run Karpenter on Fargate. 
- To forward logs on Fargate, you can create an logging configMap to use AWS' Fluent Bit log forwarder
- Fluent Bit does not support Loki yet (https://github.com/aws/containers-roadmap/issues/1242)
- We run Promtail as a sidecar instead to forward logs to Loki
- Promtail reads logs from the filesystem. 
- If `logConfig` is removed, we can no longer configure log output to the filesystem

**How important is this feature to you?**

Logging is important for us to see how Karpenter is working and the decisions it has made when debugging.

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jonathan-innis** [comment]
> Promtail reads logs from the filesystem

Can you use the `var/log/pods` path on the host to grab logs from the filesystem? Stdout and stderr logs should go over to this filepath AFAIK.

**Comment by jonathan-innis** [comment]
Looking at this deeper, I'm realizing that using Fargate would mean that you can't grab logs from the hostpath here, which is why you are indicating that you can't just use the standard stdout/stderr write-streams. I need to look a bit deeper into how Fargate expects that you scrape the logs.

This seems crazy to me that every component would have to support a separate volume output path for this to work. @calvinbui How do you handle this with other components that don't support output paths?

**Comment by calvinbui** [comment]
> How do you handle this with other components that don't support output paths?

We use Fargate to avoid having to spin up a node at the beginning in our cluster just to run Karpenter. All our nodes are created and managed by Karpenter afterwards.

**Comment by jonathan-innis** [comment]
> We use Fargate to avoid having to spin up a node at the beginning in our cluster just to run Karpenter. All our nodes are created and managed by Karpenter afterwards

Right, but I was asking more generally about how other components surface logs when it comes to fargate. I know that most kubernetes controller components don't surface output paths through their environment variable/CLI configuration so (for these components), if there's no way to access the hostPath on the node, I'd be interested to see how other components do log forwarding on Fargate.

**Comment by calvinbui** [comment]
> > We use Fargate to avoid having to spin up a node at the beginning in our cluster just to run Karpenter. All our nodes are created and managed by Karpenter afterwards
> 
> Right, but I was asking more generally about how other components surface logs when it comes to fargate. I know that most kubernetes controller components don't surface output paths through their environment variable/CLI configuration so (for these components), if there's no way to access the hostPath on the node, I'd be interested to see how other components do log forwarding on Fargate. The callout here is that I'd be surprised if this problem is unique to Karpenter.

For non-fargate hosts/pods, they have promtail, grafana agent or filebeat running as a daemonset to forward logs to their respective servers.

**Comment by jonathan-innis** [comment]
Got it. I'll pull-in some Fargate people into this conversation. I'm hoping there's a workaround to this problem outside of having to configure custom outputPaths in the logger.

**Comment by timbgn** [comment]
We are also looking at this currently.  Karpenter is spun out on Fargate and then our EKS cluster nodes are handled from there.  We already have a logging stack using fluentbit and elastic running on our kubernetes clusters so would prefer to make use of those rather than breakout in to cloudwatch.  I was hoping to make use of the logconfig options to output to a file we can then scrape via a sidecar and push in to elastic running in cluster.

**Comment by aston-r** [comment]
> I was hoping to make use of the logconfig options to output to a file we can then scrape via a sidecar and push in to elastic running in cluster.

`+ 1` native fluent-bit in fargate does not support loki, so I have to write to file and deploy flb as sidecar container.

**Comment by rschalo** [comment]
Looking at this, are you able to share some more of your configuration around Loki? For example, are errors and output sent to the same filepath?

**Comment by timbgn** [comment]
Missed the call for configs but we use the zap-logger-config to set the logs to different files and the point fluent-bit at those files to tail in to loki
`apiVersion: v1
data:
  loglevel.controller: info
  loglevel.webhook: error
  zap-logger-config: |
    {
      "level": "info",
      "development": false,
      "disableStacktrace": true,
      "disableCaller": true,
      "sampling": {
        "initial": 100,
        "thereafter": 100
      },
      "outputPaths": ["stdout", "/tmp/output.log"],
      "errorOutputPaths": ["stderr", "/tmp/error.log"],
      `

**Comment by dhanutalari** [comment]
Hi @jonathan-innis @timbgn @rschalo 
iam running karpenter controller in bottlerocket os , I am trying to forward the karpenter controller logs to graylog elastic search using filebeat. 
if i use volume mount with host path getting below error. 
Error: failed to generate container "4580c2878f037c731ae6df75dfd2fea0ca917ee252d913379d05546553fdea53" spec: failed to apply OCI options: failed to mkdir "/.bottlerocket/rootfs/var/log/pods/": mkdir /.bottlerocket: read-only file system


if i use "**shareProcessNamespace: true**" , iam getting  Permission denied

/proc/7/root/proc/34/task/40/ns': Permission denied



Please share suggestion implement fileabeat to send karpenter controller logs to elastic search.

**Comment by joshuabaird** [comment]
We also depend on `logOutput` and `errorLogOutput` to send logs to a file that is picked up by a sidecar to ship the logs.

**Comment by vijayck2020** [comment]
====================
    - name: LOG_LEVEL
      value: info
    - name: LOG_OUTPUT_PATHS
      value: "/var/log/controller.log"
    - name: LOG_ERROR_OUTPUT_PATHS
      value: stderr
    - name: METRICS_PORT
      value: "8000"

Since I am running karpenter in a fargate node, configured a ephemeral volume to be shared between controller and fluentbit containers. But the karpenter is not writing any logs to the configured file.

Is there any issues with my configuration ?


============
    # -- The container port to use for metrics.
    port: 8080
  healthProbe:
    # -- The container port to use for http health probe.
    port: 8081
webhook:
  # -- Whether to enable the webhooks and webhook permissions.
  enabled: true
  # -- The container port to use for the webhook.
  port: 8443
  metrics:
    # -- The container port to use for webhook metrics.
    port: 8001
# -- Global log level, defaults to 'info'
logLevel: info
# -- Log outputPaths - defaults to stdout only
logOutputPaths:
  - stdout
  - /var/controller.log
# -- Log errorOutputPaths - defaults to stderr only
logErrorOutputPaths:
  - stderr


This is my values file
