### ISSUE TITLE
docs: Policy in upgrading and reference wrong for v0.33 and beyond.

### ISSUE THREAD

**Issue by ksquaredkey** [aws/karpenter-provider-aws#5407]
### Description

**How can the docs be improved?**
The "v0.33/", "preview/" and "docs" versions of "reference/cloudformation.md" and "upgrading/v1beta-controller-policy.json" have the new "spot-instance-request" for CreateTags in the wrong place.  The "getting-started/getting-started-with-karpenter/cloudformation.yaml" has it set correctly.  

Unfortunately, since I was upgrading from v0.19.3 to v0.33.1, I used the policy in upgrading and lost a full day before I figured out what was wrong with that version of the policy.  This is just a doc fix to save some other poor soul from falling into the same trap.  I will follow up with a PR.

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jonathan-innis** [comment]
There's a discussion happening here (#5361) about this. I'm not convinced that we should change the v1beta1 policy to have this permission since the controller policy is only intended to be used on the v0.32.0 version and then we should rely on the [Cloudformation policy](https://github.com/aws/karpenter-provider-aws/blob/main/website/content/en/docs/getting-started/getting-started-with-karpenter/cloudformation.yaml) as the source-of-truth going forward.

My personal take is that we should:
1. Pull this policy as well as the v1beta1 migration guide out of the later versions of the docs
2. Keep the v0.32 version of the docs around for a while to support users who are upgrading to the v0.32 version
3. Redirect any reference to the v1beta1 migration guide on a newer version of the docs to the v0.32 version of the docs

**Comment by ksquaredkey** [comment]
I've put my thoughts in the other ticket but I strongly disagree with relying on the CloudFormation.   However, I will admit to having a personal bias against CloudFormation.

We can close this as duplicate.  Not sure why my GitHub search didn't find that ticket.  Then again, I didn't find the correct policy was actually present in the getting started documentation until I knew what the fix was and could search for it.

**Comment by jonathan-innis** [comment]
Closing since this is being discussed in #5361
