### ISSUE TITLE
Nodes are drifted without `EC2NodeClass.Status` being updated

### ISSUE THREAD

**Issue by engedaam** [aws/karpenter-provider-aws#5443]
### Description

**Observed Behavior**:

Currently, karpenter will use cached values for validating drift for subnets, security groups, and AMIs. Karpenter has a 5 minute reconciliation window for the EC2NodeClass status fields to be updated.  Since karpenter does not utilize the status fields for checking drift, it will appear to users that karpenter is drifting nodes that do not need to be drifted. Currently, drifted fields and the status fields are not synchronized.  

**Expected Behavior**:
When nodes are drifted, karpenter should have updated status values for subnets, security groups, and AMIs. Ideal the status condition should be used for launching, and validating drift for nodes.

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jonathan-innis** [comment]
> Since karpenter does not utilize the status fields for checking drift

Correct me if I'm wrong, but I believe that the issue is that Karpenter _does_ use the status to evaluate drift while the launch code uses the security groups/subnets/ami cache. This creates a race where the status might not have updated, but the cache has expired which means that we re-get a newer value from the cache.

This really only causes a problem when there is an AMI/subnet/security group change that happens on the cloud provider backend vs. someone making the change locally on their EC2NodeClass. It is few and far between, but we should fix this to be consistent since this effectively causes us to drift immediately after launching a node.

**Comment by njtran** [comment]
I actually sometimes see a SecurityGroupDrift happen on nodes that gets immediately un-drifted, even if there are no changes to my Security Group Selectors. Agreed that I think there's something here that we can make better

**Comment by jonathan-innis** [comment]
> SecurityGroupDrift happen on nodes that gets immediately un-drifted

Do you have a repro or an idea of specific times when this happens or does it appear pretty random?
