### ISSUE TITLE
[Environment specific setup] step04-grant-access.sh: line 1: AWS_PARTITION: unbound variable after ran make setup

### ISSUE THREAD

**Issue by francis-jjk** [aws/karpenter-provider-aws#5490]
### Description

**Observed Behavior**:
After `make setup` got error：
step04-grant-access.sh: line 1: AWS_PARTITION: unbound variable
**Expected Behavior**:
success
**Reproduction Steps** (Please include YAML):

**Versions**:
- Chart Version:
- Kubernetes Version (`kubectl version`): Client Version: v1.29.1

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jonathan-innis** [comment]
@liafizan Have you been using this Make target? I don't think that the maintainer team really uses this make target and is part of the reason that we've neglected to update it as we've made changes to the other scripts. Honestly, I'd advocate more to remove targets and scripts that aren't frequented because otherwise they just get neglected and become technical debt.

**Comment by liafizan** [comment]
hey @jonathan-innis new to project and was hoping to build this locally & run on my machine but I have not been very successful so far. Runs fine in eks. We should definitely remove targets that are not used in dev loops and may be also update contribution doc to avoid this pitfall

**Comment by jonathan-innis** [comment]
> but I have not been very successful so far

Do you have specific pain-points that you want to callout here? We are typically pointing people to: https://karpenter.sh/docs/contributing/ but if there are gaps here or there is information here that we think is out-of-date, we should definitely update that.

Ideally, there isn't a high bar to get started with Karpenter here

**Comment by liafizan** [comment]
Yup -> mainly struggle with running this locally on my machine using docker-desktop/kind. For example,
- `make run` -> does not deploy CRDs and also it tries to look for eks cluster but I am trying to run this locally. 
- `make setup` -> minor issues highlighted here. 
- `Environment setup` -> talks only about EKS & if we push an image to ECR & try to run it locally then we would also need some sort image pull creds/secrets etc 

Very minor issues which can be fixed but not sure if it's worth if people arent using local envs & those make targets. I can work on these if you feel those highlighted issues should be fixed

**Comment by jmdeal** [comment]
I'm not sure the type of local testing you're trying to do is practical for the AWS provider (though could be for [upstream](https://github.com/kubernetes-sigs/karpenter)). For functional tests we have mocked AWS APIs and rely on envtest for a lightweight test environment (pretty much just API server and ETCD iirc). For any 'real' cluster testing I think it's necessarily tied to AWS since this is the AWS provider, not necessarily EKS, though the entire maintainer team and our tests suite runs in EKS clusters so that's certainly the most tested path for our dev tooling. Would definitely like to hear more about what you're trying to achieve with a Kind cluster though.

**Comment by liafizan** [comment]
not really testing on local machine but since contribution guide + make targets provided way to run this locally, I was hoping to run this locally without having to bother with AWS/ECR etc.  I agree that we would need AWS and hence, I stopped working on local setup & focusing on AWS.

**Comment by jmdeal** [comment]
The intention of running locally is that you still target a cluster in AWS. I honestly pretty rarely do it, but it's sometimes useful as a low friction method of attaching a debugger.

**Comment by jonathan-innis** [comment]
Given that we dropped these scripts from the repo, I'm going to close-out this issue but please continue the discussion if you think that there is more conversation to be had. 

From the perspective of testing using the `make` targets from this repo, I'd say that you don't need an ECR if you have stood-up a test cluster, follow the "Getting Started" guide in the Karpenter repo on everything except for the helm install and make sure that you pass environment variables through in the same way that helm would pass them through when running and installing the binary in a container. 

I agree that this isn't necessarily called out well and we should really improve our docs around this. If you think that we're missing detail here, I'd say that we should shift this discussion over to here: https://github.com/aws/karpenter-provider-aws/issues/4884 since that issue is more about what should go in our contribution guide.

> I was hoping to run this locally without having to bother with AWS/ECR 

You could look at trying the Kwok CloudProvider if you just want to run the `kubernetes-sigs/karpenter` library and don't care about a true CloudProvider implementation: https://github.com/kubernetes-sigs/karpenter/tree/main/kwok
