### ISSUE TITLE
`kubeletConfiguration` not recognized

### ISSUE THREAD

**Issue by pazfelipe** [aws/karpenter-provider-aws#5712]
### Description

I'm trying to follow the documentation which exemplify how to fill out the few optional kubelet configuration arguments that we can manage via Karpenter, however, I'm getting a message that says the fields are not recognized.

```bash
strict decoding error: unknown field "spec.kubeletConfiguration.cpuCFSQuota", unknown field "spec.kubeletConfiguration.evictionHard", unknown field "spec.kubeletConfiguration.evictionMaxPodGracePeriod", unknown field "spec.kubeletConfiguration.evictionSoft", unknown field "spec.kubeletConfiguration.evictionSoftGracePeriod", unknown field "spec.kubeletConfiguration.imageGCHighThresholdPercent", unknown field "spec.kubeletConfiguration.imageGCLowThresholdPercent", unknown field "spec.kubeletConfiguration.kubeReserved", unknown field "spec.kubeletConfiguration.maxPods", unknown field "spec.kubeletConfiguration.podsPerCore", unknown field "spec.kubeletConfiguration.systemReserved"
```

This is api version I'm using right now

```yaml
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: karpenter
  ```

**Comment by jmdeal** [comment]
Could you provide the output from `kubectl describe crd provisioners`?

**Comment by jonathan-innis** [comment]
I think that @jmdeal is suspecting that you didn't bump your CRD as described here: https://karpenter.sh/docs/upgrading/upgrade-guide/#crd-upgrades when you came to the new controller version. Updating your CRDs to the newer version is required before updating your controller to the newer version so that you make sure that the schema that the controller is expecting is the same as the one that is actually deployed to the cluster.

Unfortunately, [helm doesn't orchestrate this process for you on a chart upgrade](https://helm.sh/docs/chart_best_practices/custom_resource_definitions/)

**Comment by jonathan-innis** [comment]
Closing since I think this is an issue with not upgrading CRDs.
