### ISSUE TITLE
v0.34.1 reproducible StorageClass bug: false positive error, misleading error message, and a suggestion

### ISSUE THREAD

**Issue by neoakris** [aws/karpenter-provider-aws#5757]
Edit: Migrated to https://github.com/kubernetes-sigs/karpenter/issues/1069, 
removing initial message to make the source of truth clear.

**Comment by jmdeal** [comment]
This is an awesome write-up, you're right that this has been a bit of a whack-a-mole problem driven by the complexity of storage in kubernetes. Would you mind reopening this in the [upstream repo](https://github.com/kubernetes-sigs/karpenter)? This is part of Karpenter's scheduling loop and I want to make sure this is visible to the other cloud providers as well, since it doesn't just affect AWS.

**Comment by neoakris** [comment]
Closing after migration, to avoid duplicate.
