### ISSUE TITLE
Decouple AWS provider release from upstream Karpenter

### ISSUE THREAD

**Issue by jmdeal** [aws/karpenter-provider-aws#5765]
Up until now, when creating a new release for the AWS Karpenter provider, we've simultaneously created a release for the upstream library ([kubernetes-sigs/karpenter](https://github.com/kubernetes-sigs/karpenter)). This has made sense historically, as the library was originally owned by AWS and the AWS provider was the only one available. Now that the library has been donated to the kubernetes sigs, and other cloudproviders exist, we should decouple our release process.

**Comment by jonathan-innis** [comment]
Should we make this a `kubernetes-sigs/karpenter` issue as well? I think that this might be relevant for Azure to hear about and be aware of as well, since the versioning in the upstream library will start to communicate meaningful information to them or any other cloudprovider building on top of the libaray

**Comment by jonathan-innis** [comment]
Going to close this one in favor of the upstream issue: https://github.com/kubernetes-sigs/karpenter/issues/1181
