### ISSUE TITLE
Different groups for provision and consolidate?

### ISSUE THREAD

**Issue by drawnwren** [aws/karpenter-provider-aws#5798]
### Description

I'm running some pods with heavy gpu loads and some pods with moderate cpu loads. I'd like to configure a nodepool such that it will conservatively spawn gpu nodes to satisfy any gpu load requirements for the gpu pods. 

Once gpu nodes have been allocated, I'd like their spare cpu to be consolidated into with my cpu pods. I'd further like to be sure that if the gpus are unallocated that the cpu workloads get consolidated off of the gpu node.

Is this something karpenter can support? I'm currently just using node affinities to make sure that gpu pods and gpu nodes are separate from the rest of my karpenter setup.

**Comment by njtran** [comment]
You could try setting up two nodepools, both with consolidation enabled. You could have your CPU pods be compatible to both NodePools, and set up a non-gpu and a gpu nodePool, with the gpu nodepool having a lower weight. Your GPU pods should be only compatible with the GPU NodePool. 

This way, CPU pods by themselves would only create your CPU-optimized instances. If you create a GPU pod, it'd only be compatible with the GPU NodePool, creating a new instance. If any new CPU pods came up later, since it's compatible with the GPU NodePool, it would likely be able to schedule on the GPU NodePool. Hope this helps.
