### ISSUE TITLE
I want to be able to specify podPidsLimit for kubelet to prevent noisy neighbour

### ISSUE THREAD

**Issue by pkobielak** [aws/karpenter-provider-aws#5828]
### Description

**What problem are you trying to solve?**

Currently there is no possibility to natively specify podPidsLimit kubelet option from Kubelet Configuration Spec. I would like to control how many pids per pod a tenant in the cluster can run to prevent noisy neighbour problem and therefore protect the nodes from fork bombs.

**How important is this feature to you?**

It is crucial to my project as I am making a multi-tenant Kubernetes platform that runs Karpenter as one of its main components.

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jonathan-innis** [comment]
> Currently there is no possibility to natively specify podPidsLimit kubelet option from Kubelet Configuration Spec. I would like to control how many pids per pod a tenant in the cluster can run to prevent noisy neighbour problem and therefore protect the nodes from fork bombs

We aren't currently supporting the full array of KubeletConfiguration options in Karpenter because of the overhead that's required for us to test out all of these fields across all AMI Families. Our general policy has been: If it doesn't affect scheduling, we aren't going to take in any new fields since there [are existing mechanisms](https://karpenter.sh/docs/concepts/nodeclasses/#specuserdata:~:text=You%20can%20also%20set%20kubelet%2Dconfig%20properties%20by%20modifying%20the%20kubelet%2Dconfig.json%20file%20before%20the%20EKS%20bootstrap%20script%20starts%20the%20kubelet) to set this through the userData in your kubelet configuration.

**Comment by jonathan-innis** [comment]
Closing in favor of #5833
