### ISSUE TITLE
Provide CR status

### ISSUE THREAD

**Issue by cdenneen** [aws/karpenter-provider-aws#5988]
### Description

Currently when listing a CR like ec2nodeclass or nodepool it lists the name and when it was created but doesn't list it's status like "Terminating" so I've had issues where the CR was in a Terminating state and stuck and would be useful to see this in the kubectl default output.

**Comment by njtran** [comment]
closing as duplicate of https://github.com/kubernetes-sigs/karpenter/issues/1152

**Comment by jonathan-innis** [comment]
This issue seems different than the issue that I opened for Nodes. It seems like having some sort of NodePool or EC2NodeClass readiness should solve this issue. We could mark the EC2NodeClass or NodePool NotReady or in a Deleting status when we are in this state. Seems like an easy way to surface this state.

**Comment by jonathan-innis** [comment]
@cdenneen It seems like there is a lot of overlap with this one: https://github.com/kubernetes-sigs/karpenter/issues/493. If we had conditions surfaced through all of our API objects (we are planning this work really soon), would this solve your use-case? If we're terminating, we can add a status condition that shows the reason like I said above. If the linked issue is correct, I think we can close this and continue discussion over there.
