### ISSUE TITLE
Pods matching multiple nodepools with the same weight

### ISSUE THREAD

**Issue by carlosrejano** [aws/karpenter-provider-aws#6049]
### Question:
We are considering an approach of having different nodepools matching the same pods, the idea behind this is to reduce the blast radius of having for example 200 nodes managed by the same nodepool and an error on this nodepool could affect all the nodes.
It’s stated in Karpenter documentation that this is not recommended:

> It is recommended to create NodePools that are mutually exclusive. So no Pod should match multiple NodePools. If multiple NodePools are matched, Karpenter will use the NodePool with the highest [weight](https://karpenter.sh/docs/concepts/nodepools/#specweight).

The idea would be having the same weight so as stated also in the doc, it should pick one of the nodepools randomly so ideally the load should be evenly spread.

> It is recommended to create NodePools that are either mutually exclusive or weighted to provide consistent scheduling behavior. If they are not and multiple NodePools are matched, Karpenter will randomly choose which to use, causing unexpected results

So I wanted to know if you have considered this use case and if you think that could introduce other problems.

**Comment by jonathan-innis** [comment]
> The idea would be having the same weight so as stated also in the doc, it should pick one of the nodepools randomly so ideally the load should be evenly spread

We haven't thought about this? Realistically, what kind of error are you thinking would have large blast radius for all of your nodes configured with that NodePool? There's a counter-argument that says that having more NodePools may also lead to more configuration errors because you may miss changes to these many NodePools as you look to make updates over time; having a smaller number makes these changes easier to manage.
