### ISSUE TITLE
Autoscaling Policy Memory Usage set to 80% usage limit

### ISSUE THREAD

**Issue by asamudrala1** [aws/karpenter-provider-aws#6091]
### Description

**What problem are you trying to solve?**
I have setup Karpenter in the EKS cluster and I am trying to set the autoscaling policy  to configure the autoscaler with the desired scaling policies. This includes specifying the target cluster and defining the resource limits for scaling. I need to specify that scaling should occur when memory usage reaches 80%. I need to configure Karpenter to monitor memory metrics and trigger scaling actions accordingly.
I am currently using https://github.com/aws/karpenter-provider-aws/archive/refs/tags/v0.34.0.tar.gz version. Could you please help in understanding what config changes need to be done to define Scaling Policy Based on Memory Usage.

**How important is this feature to you?**
Without this Karpenter is allocating 100% of its resources before it spins up a new node, which is causing the pods to fail with out of memory error. It is important for us to define the scaling policy.

**Comment by tzneal** [comment]
There isn't an option to configure a threshold.  If Pods are running out of memory, then the memory requests are too small. The memory request should be sufficient for the Pod to run.

**Comment by jonathan-innis** [comment]
I'm going to close this since this is most likely a feature that we aren't going to support. Karpenter works to maximize your nodes as much as possible. If you have configured pod requests and limits that properly match your workloads, this should result in workloads that continue to run and don't crash as well as nodes that run healthy when they are running at 100% utilization. Also, if you run this way, you're going to save costs too.

**Comment by sudhakarCSTPL** [comment]
Autoscaling Policy Memory Usage set to 80% for Spring boot apps. Java application heap once it grows, it won't release  the memory, How monitor the memory and handle heap JVM memory usage 

Can any did this.
