### ISSUE TITLE
Support configuring cpu options via ec2nodeclass

### ISSUE THREAD

**Issue by maxsargentdev** [aws/karpenter-provider-aws#6092]
### Description

**What problem are you trying to solve?**

I would like to be able to disable hyperthreading on a node launched by karpenter, via the ec2nodeclass resource.

Using terraform you can create AWS launch templates that disable this feature: 

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/launch_template#cpu-options

I have achieved this previously with karpenter using a custom launch template and a provisioner.

**How important is this feature to you?**

I cannot upgrade to the newest APIs without this feature, so very important.

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by engedaam** [comment]
I think this would go in head with more expendable launch template support, no? https://github.com/aws/karpenter-provider-aws/issues/3369. How do you feel about closing this as a duplicate and adding your use case in that conversion?

**Comment by maxsargentdev** [comment]
I am happy to do so.

Sadly there is no migration path for my current workload because of this, I will have to stay on the old API until this feature is added then do a migration all the way to the version with this feature.

Thanks for replying and working on a great project tho it's been really useful for my organisation 👍

**Comment by maxsargentdev** [comment]
Feel free to close as duplicate.

**Comment by alex-berger** [comment]
https://github.com/aws/karpenter-provider-aws/issues/3369 is not making any progress, and for example disabling HyperThreading (HT) via [CPU Options](https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-properties-ec2-launchtemplate-cpuoptions.html) is a security best practice (to protect against a whole class of side channel attacks) that should have first class support in EC2NodeClass. End-users shoule not have to revert to LanuchTemplates (LT) or any other complex solution to implement security best practices. Furthermore, there are also use-cases that need disabling HyperThreading for licensing reasons, for example for expensive vCPU based products, where one otherwise pays a full vCPU license for the (not-so-powerfull) HyptherThread fake core.

@engedaam I propose to reopen this issue to encourage (PR) contributions for this.

**Comment by strelok89** [comment]
https://aws.amazon.com/about-aws/whats-new/2025/10/amazon-ec2-cpu-options-optimization-license-included-instances/

After this feature the option to disable HT in karpenter is really a necessity
