### ISSUE TITLE
Need Suggestion on how to run a workload

### ISSUE THREAD

**Issue by abhikapstan** [aws/karpenter-provider-aws#6129]
### Description

**Observed Behavior**:
We run a kubernetes cluster which mostly requires 4-5 aws nodes. We run applications with 1 pod to save cost and it runs fine. For few days we are noticing that karpenter consolidates very aggressively and it could cause downtime and like in one day it consolidated 3 times. We do not use autoscale so pods go up and down so that is not the case.

**Expected Behavior**:
Do we have suggestion that karpenter does not scale that aggressively. We do not want to turn off consolidation.

Also i have a question regrading replacement. When karpenter marks a node for deletion does it make sure that a new pod has been created for every pod it is going to delete ? Because we have seen it does not

Can we disable multi node consolidation policy. We may only want one node to go down at a time

**Reproduction Steps** (Please include YAML):
This is our node pool config

```

{
    "apiVersion" = "karpenter.sh/v1beta1"
    "kind" = "NodePool"
    "metadata" = {
      "name" = "karpenter"
    }
    "spec" = {
      "disruption" = {
        "consolidationPolicy" = "WhenUnderutilized"
        "expireAfter" = "Never"
      }
      "limits" = {
        "cpu" = "20"
        "memory" = "50Gi"
      }
      "template" = {
        "metadata" = {}
        "spec" = {
          "nodeClassRef" = {
            "name" = "karpenter-ec2-node-class"
          }
          "requirements" = [
            {
              "key" = "karpenter.sh/capacity-type"
              "operator" = "In"
              "values" = [
                "on-demand",
              ]
            },
            {
              "key" = "karpenter.k8s.aws/instance-category"
              "operator" = "In"
              "values" = [
                "c",
                "m",
                "r",
              ]
            },
            {
              "key" = "karpenter.k8s.aws/instance-size"
              "operator" = "NotIn"
              "values" = [
                "nano",
                "micro",
                "small",
                "medium",
              ]
            },
            {
              "key" = "karpenter.k8s.aws/instance-generation"
              "operator" = "In"
              "values" = [
                "6",
                "7",
              ]
            },
            {
              "key" = "kubernetes.io/arch"
              "operator" = "In"
              "values" = [
                "arm64",
              ]
            },
            {
              "key" = "kubernetes.io/os"
              "operator" = "In"
              "values" = [
                "linux",
              ]
            },
          ]
        }
      }
    }
  }
  
  ```
**Versions**:
- Chart Version: 0.32.5
- Kubernetes Version (`kubectl version`): 1.28

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by abhikapstan** [comment]
I field it as bug because i am not sure if it qualifies as feature request

**Comment by jmdeal** [comment]
You can't explicitly disable multi-node consolidation, but you can use disruption budgets to limit the number of nodes being disrupted in parallel: https://karpenter.sh/docs/concepts/disruption/#disruption-budgets. Setting a budget for a single node should achieve the behavior you want, but note that this doesn't only affect consolidation but all forms of voluntary disruption (i.e. drift and expiration). 

As for your issues with application stability, Karpenter doesn't create new pods for your deployment when processing disruptions. We don't begin draining the disrupted node until the replacement node is ready, but there will still be a moment of downtime when pods are evicted from one node and scheduled to another. Karpenter does respect PDBs and PDBs should be configured such that disruption doesn't cause an application outage. This won't work if you only have a single pod, is your application horizontally scalable? I know you mentioned you're running a single pod to save costs, could running multiple smaller pods be a viable alternative? 

Changed this to a feature request since Karpenter doesn't currently support creating additional pods when disrupting nodes.
