### ISSUE TITLE
creating node claim, create not allowed

### ISSUE THREAD

**Issue by sree42111** [aws/karpenter-provider-aws#6162]
### Description

**Observed Behavior**:
while upgrading From V35 to V36 Karpenter pod is showing the error . ERROR","time":"2024-05-07T08:20:24.584Z","logger":"controller.provisioner","message":"creating node claim, create not allowed while custom resource definition is terminating; creating node claim, create not allowed while custom resource definition is terminating; creating node claim, create not allowed while custom resource definition is terminating","commit":"fb4

During the upgrade process, I encountered an error. To resolve it, I manually deleted the ec2nodeclasses.karpenter.k8s.aws CustomResourceDefinition (CRD) using kubectl delete CustomResourceDefinition ec2nodeclasses.karpenter.k8s.aws. After reinstalling the CRD, I noticed that Karpenter is no longer scheduling pending pods.

Tried removing ec2nodeclass and nodepool and reapplied result is same 

**Expected Behavior**:

**Reproduction Steps** (Please include YAML):

**Versions**:0.36.1
- Chart Version:0.36
- Kubernetes Version (`kubectl version`):1.29

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jonathan-innis** [comment]
@sree42111 It looks like whatever process you applied for upgrade caused the CRD to get deleted. Once you are in this state, you can't go back from it until the CRD gets fully deleted. So, I think you need to deprovision all of the NodeClaim resources so that the CRD can get safely removed. And then, you can re-install the CRD on the new version.

In the future, you should just upgrade the CRD in-place (a good way to do this is described [here](https://karpenter.sh/docs/upgrading/upgrade-guide/#crd-upgrades)).

**Comment by sree42111** [comment]
yes,correct kubectl edit CustomResourceDefinition nodeclaims.karpenter.sh removed the finializer field and reinstalled latest CRD solved the issue.

**Comment by jonathan-innis** [comment]
Great, closing this issue since it appears to be solved now.
