### ISSUE TITLE
Support karpenter.sh/do-not-disrupt on namespace level

### ISSUE THREAD

**Issue by pragmaticivan** [aws/karpenter-provider-aws#6392]
### Description

**What problem are you trying to solve?**
I could not find docs, so I'm proposing this becomes a feature.

Given a namespace `critical`, I would like to add `karpenter.sh/do-not-disrupt = true` to the namespace, so that any pod under that namespace can't be disrupted.

**How important is this feature to you?**

This would be ideal for multi-tenant clusters where you want to incrementally onboard teams into disruption schedules.

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jigisha620** [comment]
This issue seems more related to [kubernetes-sigs/karpenter](https://github.com/kubernetes-sigs/karpenter/issues) than being specific to AWS. Also we already have an issue open for this in upstream - https://github.com/kubernetes-sigs/karpenter/issues/1189. Can you close this issue in favor of the upstream issue? Feel free to comment on that issue with your use case for this feature. Thanks!

**Comment by pragmaticivan** [comment]
yes, thx!
