### ISSUE TITLE
Donate to CNCF

### ISSUE THREAD

**Issue by alvsanand** [aws/karpenter-provider-aws#6439]
### Description

**What problem are you trying to solve?**
As one of the top 5 Kubernetes autoscaler of the market, being a project in the CNCf will incentive other providers to adopt this awesome product. More provider, means more devs contributing to it and more features for the users. Big quick-win.

**How important is this feature to you?**
Being in the CNCF provides more guarantees that it will be maintained in time and also compatibility with other providers in case our companies decide to change it.

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jonathan-innis** [comment]
See: https://github.com/kubernetes/org/issues/4258. This was done for the upstream library (`kubernetes-sigs/karpenter`). There's no current plans to donate the specific providers since they are CloudProvider-specific implementations and can be owned by the CloudProvider.

Are you interested in the upstream repo or the CloudProvider repo being donated?

**Comment by alvsanand** [comment]
Thanks for the answer and sorry for the misunderstanding. I did not know that the core was donated. Great job done
