### ISSUE TITLE
Allocatable memory less than actual memory during scheduling (trn1.32x)

### ISSUE THREAD

**Issue by WxFang** [aws/karpenter-provider-aws#6509]
### Description

**Observed Behavior**:
We are migrating from CAS to Karpenter but found scheduling issues for nodepools using `trn1.32x`. 
Basically during scheduling, we can see the event log as below complaining no instance type found. This higher than `481894Mi ` which is the [instance type spec given by Karpenter](https://karpenter.sh/preview/reference/instance-types/#trn132xlarge) which is fine. 

```
Failed to schedule pod, incompatible with nodepool "trn1.32x", daemonset overhead=
{"cpu":"280m","memory":"376Mi","pods":"7"}, no instance type satisfied resources
{"aws.amazon.com/neuron":"16","cpu":"124280m","memory":"498431899Ki","pods":"8"} and requirements
karpenter.sh/capacity-type In [on-demand], karpenter.sh/nodepool In [trn1.32x], kubernetes.io/arch In [amd64],
kubernetes.io/os In [linux], node.kubernetes.io/instance-type In [trn1.32xlarge], nodepool In [trn1.32x] 
(no instance type has enough resources)
```
But after we tuned down the ram request and the node scaled up, the actual allocatable memory is much higher (**22Gi**), close to what we used to have when using CAS. 
So our question is that is this behavior as expected? How can we tune the system/kubelet reserve during scheduling?

**Reproduction Steps** (Please include YAML):

**actual allocatable resource:**
```
Allocatable:
  aws.amazon.com/neuron:        16
  aws.amazon.com/neuroncore:    32
  aws.amazon.com/neurondevice:  16
  cpu:                          127610m
  ephemeral-storage:            482098735124
  hugepages-1Gi:                0
  hugepages-2Mi:                256Mi
  memory:                       516634508Ki
  pods:                         247
```

**Versions**:
- Chart Version:
- Kubernetes Version (`kubectl version`):

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jmdeal** [comment]
Karpenter has a concept called `VM_MEMORY_OVERHEAD_PERCENT`. This is used to model the arbitrary amount of memory that isn't available due to AMI / other instance overhead. This is separate from system of kubelet reservations, which Karpenter does model. There isn't a good way to model this accurately, so the default value (7.5%) is used since it doesn't overestimate the amount of memory available on 99% of instance types. If you know the overhead for the instances you're using in your cluster, you could tune this value to get a closer estimate. [RFC: NodeOverlay](https://github.com/kubernetes-sigs/karpenter/pull/1305) may also help address this by allowing per-instance type overrides.

**Comment by WxFang** [comment]
Thanks for the explanation!
I have two questions:
1. can we also configure cpu overhead?
2. seems like the param is for the whole cluster not nodepool/instance type specific?
