### ISSUE TITLE
How can I set the SpotPrice?

### ISSUE THREAD

**Issue by changhyuni** [aws/karpenter-provider-aws#6816]
### Description

**What problem are you trying to solve?**
how can I set the SportPrice?
```
SpotPrice (string) –

The maximum price per unit hour that you are willing to pay for a Spot Instance. We do not recommend using this parameter because it can lead to increased interruptions. If you do not specify this parameter, you will pay the current Spot price.
```
**How important is this feature to you?**
Where can I set this? If it doesn't exist, why not? Is it a value that doesn't mean much?

**Comment by jmdeal** [comment]
This is currently not configurable within Karpenter. IIUC how it works, I'm not sure it's something we would want to support in Karpenter either. I'm not sure why we would want to limit the maximum price of a single spot instance, since that could just cause Karpenter to provision multiple smaller instances instead of one larger instance (which may have been cheaper overall). What use-cases do you have in mind for this?

**Comment by kiawnna** [comment]
@jmdeal 
I have a use case - let me know if this makes sense.

We utilize g4dn.xlarge instances. Sometimes, these aren't enough available, and we would like to use g4dn.2xlarge and g4dn.4xlarge instances types to attempt to broaden our spot availability.

BUT we only ever want the spot price for those other two large instances to be equal to the xlarge on-demand price (otherwise we'll just fallback to the on-demand, since we don't actually need the extra compute power, and we also can't put more pods on the larger instances because we can only run 6 models per GPU).

**Comment by jmdeal** [comment]
You should actually be able to achieve this today. If you have a mixed spot / on-demand nodepool, Karpenter will choose to launch with on-demand if there is an on-demand instance available that is cheaper than the cheapest spot instance. If I understand correctly, this should meet your use case. If this isn't working for you, please go ahead and open a new issue.

**Comment by changhyuni** [comment]
What @kiawnna asked is exactly what I wanted to know as well. 

@jmdeal 
Thanks for the explanation! So does that mean the current version of Karpenter will allocate instances based on the lowest cost first?

**Comment by jmdeal** [comment]
Not quite, with spot the [price-capacity optimized](https://aws.amazon.com/blogs/compute/introducing-price-capacity-optimized-allocation-strategy-for-ec2-spot-instances/) allocation strategy is used. This provides a balance of cost and interruption optimization. But consider this example: `g4dn.xlarge` is unavailable via spot, the larger instances are, but your NodePool is flexible to both spot and on-demand. In this case, if the on-demand price for `g4dn.xlarge` is cheaper than the available spot instances, Karpenter will launch it as on-demand. I realize this isn't perfect in theory - if the `g4dn.xlarge` is available but capacity is constrained, it is possible that `CreateFleet` will choose to launch with a more expensive instance. That being said, if there are large gaps in price I don't expect that to happen in practice.

**Comment by kiawnna** [comment]
Yeah so my issue is exactly that though -- we are consistently losing spot capacity (which is fine, that's what spot is haha) and therefore I don't want all the instance sizes in the same node pool because I do not want to launch 2xlarge or 4xlarge with on-demand pricing, and I'm sure how likely it is that would happen... maybe I just need to experiment some. Thanks for all your detailed answers!!
