### ISSUE TITLE
Karpenter: "no instance types satisfy requirements of ami" even though there are no constraints on NodePool

### ISSUE THREAD

**Issue by MedAzizTousli** [aws/karpenter-provider-aws#7211]
### Description

This problem has been bugging me a lot since I have deployed Karpenter in my EKS cluster. Basically, Karpenter says that AMI requirements are not met even though I have not set up any constraints in the NodeLabels.

This is the error log message:

    {"level":"ERROR","time":"2024-10-14T05:52:56.624Z","logger":"controller","message":"Reconciler error","commit":"6174c75","controller":"nodeclaim.lifecycle","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","NodeClaim":{"name":"kafka-nodepool-7dd28"},"namespace":"","name":"kafka-nodepool-7dd28","reconcileID":"fc714779-d1be-45d1-a52a-a73b8c96230c","error":"launching nodeclaim, creating instance, getting launch template configs, getting launch templates, no instance types satisfy requirements of amis [ami-06d9bcac32f727ddb]"}
This is my `EC2NodeClass`, and `NodePool` (I have four other NodePools that are completely similar to the `dbs-nodepool`, except for the custom `node-group` label):
```yaml
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default-nodeclass
spec:
  kubelet:
    maxPods: 110
  amiFamily: AL2
  role: "fg-eks-node-iam-002"
  securityGroupSelectorTerms:
    - id: "sg-06b14fe60bc984ed4"
  subnetSelectorTerms:
    - id: "subnet-04da6cc8e9d66b4ae"
  amiSelectorTerms:
    - id: "ami-06d9bcac32f727ddb"
--- # dbs, kafka, monitoring, staging, prod
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: dbs-nodepool
spec:
  template:
    spec:
      requirements:
        - key: node-group
          operator: In
          values: ["dbs"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand"]
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: default-nodeclass
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 1m
```
These are the currently deployed nodes with the same AMI (Karpenter was able to find nodes for the AMI here, but still generates the above error for some reason).
[![enter image description here][1]][1]

  [1]: https://i.sstatic.net/KProREwG.png

**Comment by jmdeal** [comment]
I believe I understand the root cause of the error in both cases, but will need some more details to verify. 

In @MedAzizTousli's case, you're specifying a single AMI id in your AMI selector terms. I assume, based on the instance types you've successfully launched, that this is an `amd64` AMI. However, you're `NodePool` is open to both `amd64` and `arm64` instance types. What I suspect is happening is that a NodeClaim is created which is only compatible with `arm64` instance types, either due to a constraint on a pod in your cluster or because the 60 cheapest, compatible instances are all `arm64`. Either way, adding an `amd64` architecture requirement to your `NodePool` should fix this. We can verify this is the case by looking at the status of your `EC2NodeClass` and looking at the manifest of one of the NodeClaims in your errors.

In @dborysenko's case, I suspect a NodeClaim is being created which is only compatible with `g5g` instances. There are no EKS-optimized AL2/AL2023 accelerated AMIs for `arm64` instances at the moment, leading to this error. There are accelerated `amd64` AMIs and non-accelerated `arm64` AMIs though, hence why `g6` and `c6g` instances work respectively. We can take a look at the status condition on your NodeClass and the manifest from a NodeClaim in your errors to verify.

**Comment by dborysenko** [comment]
@jmdeal Thanks a lot for taking a look. Please find requested information below

<details>
  <Summary>Nodeclaim</Summary >

```yaml
apiVersion: karpenter.sh/v1
kind: NodeClaim
metadata:
  annotations:
    karpenter.sh/nodepool-hash: '12328812915589085382'
    karpenter.sh/nodepool-hash-version: v3
    karpenter.sh/stored-version-migrated: 'true'
  creationTimestamp: '2024-10-17T16:19:08Z'
  finalizers:
    - karpenter.sh/termination
  generateName: mv-ng01-
  generation: 1
  labels:
    karpenter.sh/nodepool: mv-ng01
  name: mv-ng01-sqvkd
  ownerReferences:
    - apiVersion: karpenter.sh/v1
      blockOwnerDeletion: true
      kind: NodePool
      name: mv-ng01
      uid: 156b1c8c-107a-4a3b-bc0d-9a1fe6e65c71
  resourceVersion: '303035461'
  uid: ae81e1ac-0b60-4a3d-a3f6-6f6af24cc5a3
  selfLink: /apis/karpenter.sh/v1/nodeclaims/mv-ng01-sqvkd
status:
  conditions:
    - lastTransitionTime: '2024-10-17T16:19:08Z'
      message: Node not registered with cluster
      reason: NodeNotFound
      status: Unknown
      type: Initialized
    - lastTransitionTime: '2024-10-17T16:19:08Z'
      message: >-
        creating instance, getting launch template configs, getting launch
        templates, no instance types satisfy requirements of amis
        [ami-0a4ab1b558a556873 ami-0c94344185d904936 ami-0f472452b5db6f495]
      reason: LaunchFailed
      status: Unknown
      type: Launched
    - lastTransitionTime: '2024-10-17T16:19:08Z'
      message: Initialized=Unknown, Registered=Unknown, Launched=Unknown
      reason: UnhealthyDependents
      status: Unknown
      type: Ready
    - lastTransitionTime: '2024-10-17T16:19:08Z'
      message: Node not registered with cluster
      reason: NodeNotFound
      status: Unknown
      type: Registered
spec:
  expireAfter: Never
  nodeClassRef:
    group: karpenter.k8s.aws
    kind: EC2NodeClass
    name: mv-ng01
  requirements:
    - key: eks.amazonaws.com/nodegroup
      operator: In
      values:
        - mv-ng01
    - key: karpenter.k8s.aws/instance-family
      operator: In
      values:
        - g5g
    - key: topology.kubernetes.io/zone
      operator: In
      values:
        - us-west-2a
        - us-west-2b
    - key: karpenter.sh/capacity-type
      operator: In
      values:
        - on-demand
    - key: karpenter.sh/nodepool
      operator: In
      values:
        - mv-ng01
    - key: node.kubernetes.io/instance-type
      operator: In
      values:
        - g5g.16xlarge
        - g5g.2xlarge
        - g5g.4xlarge
        - g5g.8xlarge
        - g5g.metal
        - g5g.xlarge
  resources:
    requests:
      cpu: 1150m
      memory: 740Mi
      pods: '8'

```
</details>
<details>
  <Summary>Nodeclass Status Conditions</Summary>

```yaml

  conditions:
    - lastTransitionTime: '2024-10-16T19:48:31Z'
      message: ''
      reason: AMIsReady
      status: 'True'
      type: AMIsReady
    - lastTransitionTime: '2024-10-16T19:48:31Z'
      message: ''
      reason: InstanceProfileReady
      status: 'True'
      type: InstanceProfileReady
    - lastTransitionTime: '2024-10-16T19:48:31Z'
      message: ''
      reason: Ready
      status: 'True'
      type: Ready
    - lastTransitionTime: '2024-10-16T19:48:31Z'
      message: ''
      reason: SecurityGroupsReady
      status: 'True'
      type: SecurityGroupsReady
    - lastTransitionTime: '2024-10-16T19:48:31Z'
      message: ''
      reason: SubnetsReady
      status: 'True'
      type: SubnetsReady

```

</details>

**Comment by jmdeal** [comment]
Ok, it looks like AMIs are ready but the NodeClaim requires `g5g` instances. This isn't going to be compatible with the `al2` alias since it doesn't have a compatible AMI associated with it. The only alias with a compatible AMI is going to be Bottlerocket at the moment.

**Comment by dborysenko** [comment]
You are right. In NodeClass going from alias to
```yaml
  amiFamily: AL2023
  amiSelectorTerms:
    - name: amazon-eks-node-al2023-arm64-standard-1.30-v20241011
```
makes me able to schedule workload on g5g instances.
That's unfortunate though that g5g is not compatible with alias, kinda requires special treatment.

**Comment by jmdeal** [comment]
I am curious, are you installing all of the required GPU drivers and kernel modules through UserData or some other method out of band? We don't consider the standard `arm64` AMI compatible since it won't work out of the box, and typically a custom AMI would be used for that use case. Though I did notice your `NodeClaim` didn't have an GPU requests; are you using the instance for workloads that don't require GPUs?

**Comment by dborysenko** [comment]
We have not gotten that far yet, probably gonna do UserData.

**Comment by MedAzizTousli** [comment]
Thank you very much @jmdeal. The issue and the solution were indeed as you said. I had to limit Karpenter to the architecture that the AMI was built for (which is in my case `amd64`. I am marking the issue as resolved.
