### ISSUE TITLE
How to configure disruption to stop scheduling on instance with only workloads marked to not disrupt

### ISSUE THREAD

**Issue by tauanlemos** [aws/karpenter-provider-aws#7299]
## Description
I have some workloads consisting of long running jobs that I want to ensure are finished. So I marked those workloads with the label `karpenter.sh/do-not-disrupt`. But, since this prevents the node to be marked for disruption, new workloads (of the same type) are being assigned to the node. Is there a way for me to configure the disruption so that it will stop scheduling pods on the node that should have been marked for disruption, so it can be "drained out", and start assign pods to a new node ?

I have checked the documentation on disruption but I see no way of customizing for the behaviour I need. 

Thank you

**Comment by Ardarel** [comment]
I am experiencing the same issue. I am using GitLab runners. During peak usage, nodes with more than 500GB of memory are sometimes created. However, after the spike, these nodes remain almost empty because one or two jobs are always scheduled, preventing the node from being terminated. I would like the possibility to cordon the node when there is an attempt to disrupt it.

**Comment by engedaam** [comment]
Have you considered using [terminationGracePeirod](https://karpenter.sh/docs/concepts/disruption/#terminationgraceperiod)?

**Comment by tauanlemos** [comment]
I'll try the terminationGracePeriod. The problem is that I dont have a way of really knowking how long the jobs will take. But I'll give a long enough grace period to ensure our longest running jobs finishes.  Thanks

**Comment by SaiKiranChary-Poloju** [comment]
@tauanlemos Have you found a solution or workaround for this ?
